In [1]:
import numpy as np

In [11]:
# 0-D

arr= np.array(2)
print(arr)
print(arr.ndim) #  ndim means no. of dimension

2
0


In [16]:
# 1-D

arr = np.array([1,2,3,4,5])
print(arr)
print('no. of dimension: ', arr.ndim , ';  datatype :', arr.dtype)

[1 2 3 4 5]
no. of dimension:  1 ;  datatype : int32


In [25]:
arr = np.array([1,2,3,4,5, 'punit'] ,dtype='S')
print(arr)
print('no. of dimension: ', arr.ndim , ';  datatype :', arr.dtype)

[b'1' b'2' b'3' b'4' b'5' b'punit']
no. of dimension:  1 ;  datatype : |S5


In [26]:
print(arr)

[b'1' b'2' b'3' b'4' b'5' b'punit']


In [28]:
#  2-D

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('no. of dimension: ', arr.ndim , ';  datatype :', arr.dtype)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
no. of dimension:  2 ;  datatype : int32


In [37]:
from numpy import random
x = random.binomial(n=10, p=0.5, size=10)

print(x)

[6 2 6 7 2 6 5 2 8 6]


In [38]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
sns.distplot(random.binomial(n=5, p=0.5, size=10), hist=True, kde=False)

plt.show()

